	soc_system u0 (
		.clk_clk                             (<connected-to-clk_clk>),                             //                     clk.clk
		.hps_0_f2h_sdram0_data_address       (<connected-to-hps_0_f2h_sdram0_data_address>),       //   hps_0_f2h_sdram0_data.address
		.hps_0_f2h_sdram0_data_burstcount    (<connected-to-hps_0_f2h_sdram0_data_burstcount>),    //                        .burstcount
		.hps_0_f2h_sdram0_data_waitrequest   (<connected-to-hps_0_f2h_sdram0_data_waitrequest>),   //                        .waitrequest
		.hps_0_f2h_sdram0_data_readdata      (<connected-to-hps_0_f2h_sdram0_data_readdata>),      //                        .readdata
		.hps_0_f2h_sdram0_data_readdatavalid (<connected-to-hps_0_f2h_sdram0_data_readdatavalid>), //                        .readdatavalid
		.hps_0_f2h_sdram0_data_read          (<connected-to-hps_0_f2h_sdram0_data_read>),          //                        .read
		.hps_0_h2f_lw_axi_master_awid        (<connected-to-hps_0_h2f_lw_axi_master_awid>),        // hps_0_h2f_lw_axi_master.awid
		.hps_0_h2f_lw_axi_master_awaddr      (<connected-to-hps_0_h2f_lw_axi_master_awaddr>),      //                        .awaddr
		.hps_0_h2f_lw_axi_master_awlen       (<connected-to-hps_0_h2f_lw_axi_master_awlen>),       //                        .awlen
		.hps_0_h2f_lw_axi_master_awsize      (<connected-to-hps_0_h2f_lw_axi_master_awsize>),      //                        .awsize
		.hps_0_h2f_lw_axi_master_awburst     (<connected-to-hps_0_h2f_lw_axi_master_awburst>),     //                        .awburst
		.hps_0_h2f_lw_axi_master_awlock      (<connected-to-hps_0_h2f_lw_axi_master_awlock>),      //                        .awlock
		.hps_0_h2f_lw_axi_master_awcache     (<connected-to-hps_0_h2f_lw_axi_master_awcache>),     //                        .awcache
		.hps_0_h2f_lw_axi_master_awprot      (<connected-to-hps_0_h2f_lw_axi_master_awprot>),      //                        .awprot
		.hps_0_h2f_lw_axi_master_awvalid     (<connected-to-hps_0_h2f_lw_axi_master_awvalid>),     //                        .awvalid
		.hps_0_h2f_lw_axi_master_awready     (<connected-to-hps_0_h2f_lw_axi_master_awready>),     //                        .awready
		.hps_0_h2f_lw_axi_master_wid         (<connected-to-hps_0_h2f_lw_axi_master_wid>),         //                        .wid
		.hps_0_h2f_lw_axi_master_wdata       (<connected-to-hps_0_h2f_lw_axi_master_wdata>),       //                        .wdata
		.hps_0_h2f_lw_axi_master_wstrb       (<connected-to-hps_0_h2f_lw_axi_master_wstrb>),       //                        .wstrb
		.hps_0_h2f_lw_axi_master_wlast       (<connected-to-hps_0_h2f_lw_axi_master_wlast>),       //                        .wlast
		.hps_0_h2f_lw_axi_master_wvalid      (<connected-to-hps_0_h2f_lw_axi_master_wvalid>),      //                        .wvalid
		.hps_0_h2f_lw_axi_master_wready      (<connected-to-hps_0_h2f_lw_axi_master_wready>),      //                        .wready
		.hps_0_h2f_lw_axi_master_bid         (<connected-to-hps_0_h2f_lw_axi_master_bid>),         //                        .bid
		.hps_0_h2f_lw_axi_master_bresp       (<connected-to-hps_0_h2f_lw_axi_master_bresp>),       //                        .bresp
		.hps_0_h2f_lw_axi_master_bvalid      (<connected-to-hps_0_h2f_lw_axi_master_bvalid>),      //                        .bvalid
		.hps_0_h2f_lw_axi_master_bready      (<connected-to-hps_0_h2f_lw_axi_master_bready>),      //                        .bready
		.hps_0_h2f_lw_axi_master_arid        (<connected-to-hps_0_h2f_lw_axi_master_arid>),        //                        .arid
		.hps_0_h2f_lw_axi_master_araddr      (<connected-to-hps_0_h2f_lw_axi_master_araddr>),      //                        .araddr
		.hps_0_h2f_lw_axi_master_arlen       (<connected-to-hps_0_h2f_lw_axi_master_arlen>),       //                        .arlen
		.hps_0_h2f_lw_axi_master_arsize      (<connected-to-hps_0_h2f_lw_axi_master_arsize>),      //                        .arsize
		.hps_0_h2f_lw_axi_master_arburst     (<connected-to-hps_0_h2f_lw_axi_master_arburst>),     //                        .arburst
		.hps_0_h2f_lw_axi_master_arlock      (<connected-to-hps_0_h2f_lw_axi_master_arlock>),      //                        .arlock
		.hps_0_h2f_lw_axi_master_arcache     (<connected-to-hps_0_h2f_lw_axi_master_arcache>),     //                        .arcache
		.hps_0_h2f_lw_axi_master_arprot      (<connected-to-hps_0_h2f_lw_axi_master_arprot>),      //                        .arprot
		.hps_0_h2f_lw_axi_master_arvalid     (<connected-to-hps_0_h2f_lw_axi_master_arvalid>),     //                        .arvalid
		.hps_0_h2f_lw_axi_master_arready     (<connected-to-hps_0_h2f_lw_axi_master_arready>),     //                        .arready
		.hps_0_h2f_lw_axi_master_rid         (<connected-to-hps_0_h2f_lw_axi_master_rid>),         //                        .rid
		.hps_0_h2f_lw_axi_master_rdata       (<connected-to-hps_0_h2f_lw_axi_master_rdata>),       //                        .rdata
		.hps_0_h2f_lw_axi_master_rresp       (<connected-to-hps_0_h2f_lw_axi_master_rresp>),       //                        .rresp
		.hps_0_h2f_lw_axi_master_rlast       (<connected-to-hps_0_h2f_lw_axi_master_rlast>),       //                        .rlast
		.hps_0_h2f_lw_axi_master_rvalid      (<connected-to-hps_0_h2f_lw_axi_master_rvalid>),      //                        .rvalid
		.hps_0_h2f_lw_axi_master_rready      (<connected-to-hps_0_h2f_lw_axi_master_rready>),      //                        .rready
		.hps_0_h2f_reset_reset_n             (<connected-to-hps_0_h2f_reset_reset_n>),             //         hps_0_h2f_reset.reset_n
		.hps_0_i2c1_out_data                 (<connected-to-hps_0_i2c1_out_data>),                 //              hps_0_i2c1.out_data
		.hps_0_i2c1_sda                      (<connected-to-hps_0_i2c1_sda>),                      //                        .sda
		.hps_0_i2c1_clk_clk                  (<connected-to-hps_0_i2c1_clk_clk>),                  //          hps_0_i2c1_clk.clk
		.hps_0_i2c1_scl_in_clk               (<connected-to-hps_0_i2c1_scl_in_clk>),               //       hps_0_i2c1_scl_in.clk
		.memory_mem_a                        (<connected-to-memory_mem_a>),                        //                  memory.mem_a
		.memory_mem_ba                       (<connected-to-memory_mem_ba>),                       //                        .mem_ba
		.memory_mem_ck                       (<connected-to-memory_mem_ck>),                       //                        .mem_ck
		.memory_mem_ck_n                     (<connected-to-memory_mem_ck_n>),                     //                        .mem_ck_n
		.memory_mem_cke                      (<connected-to-memory_mem_cke>),                      //                        .mem_cke
		.memory_mem_cs_n                     (<connected-to-memory_mem_cs_n>),                     //                        .mem_cs_n
		.memory_mem_ras_n                    (<connected-to-memory_mem_ras_n>),                    //                        .mem_ras_n
		.memory_mem_cas_n                    (<connected-to-memory_mem_cas_n>),                    //                        .mem_cas_n
		.memory_mem_we_n                     (<connected-to-memory_mem_we_n>),                     //                        .mem_we_n
		.memory_mem_reset_n                  (<connected-to-memory_mem_reset_n>),                  //                        .mem_reset_n
		.memory_mem_dq                       (<connected-to-memory_mem_dq>),                       //                        .mem_dq
		.memory_mem_dqs                      (<connected-to-memory_mem_dqs>),                      //                        .mem_dqs
		.memory_mem_dqs_n                    (<connected-to-memory_mem_dqs_n>),                    //                        .mem_dqs_n
		.memory_mem_odt                      (<connected-to-memory_mem_odt>),                      //                        .mem_odt
		.memory_mem_dm                       (<connected-to-memory_mem_dm>),                       //                        .mem_dm
		.memory_oct_rzqin                    (<connected-to-memory_oct_rzqin>),                    //                        .oct_rzqin
		.reset_reset_n                       (<connected-to-reset_reset_n>)                        //                   reset.reset_n
	);

